### ISSUE TITLE
Add Readme with instructions for use

### ISSUE THREAD

**Issue by gabfiocchi** [fivethree-team/ionic-4-fastlane-plugin#4]
Hi guys, we have found this amazing work you have done with Fastlante and Ionic 4, but we've noticed that there are no instructions on how to use this correctly, any chances you can make a README 😄?

Keep Rocking! 🚀 

Thanks,

**Comment by marcjulian** [comment]
We have started adding instructions to the [README](https://github.com/fivethree-team/ionic-4-fastlane-plugin#readme) and also added some examples to [Fastfile](https://github.com/fivethree-team/ionic-4-fastlane-plugin/blob/master/fastlane-plugin-fivethree_ionic/fastlane/Fastfile)
